In [1]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn.datasets import load_iris
X, y = load_iris().data, load_iris().target

k= 5
kmeans = KMeans(n_clusters= k)
y_pred = kmeans.fit_predict(X)
print(y_pred)
# 分类的实例标签是该实例被分配给该集群的索引
print(y_pred is kmeans.labels_)

# 查看一下算法发现的5个算法中心点
kmeans.cluster_centers_

[4 0 0 0 4 4 0 4 0 0 4 0 0 0 4 4 4 4 4 4 4 4 0 4 0 0 4 4 4 0 0 4 4 4 0 0 4
 4 0 4 4 0 0 4 4 0 4 0 4 0 1 1 1 3 1 3 1 3 1 3 3 3 3 1 3 1 3 3 1 3 1 3 1 1
 1 1 1 1 1 3 3 3 3 1 3 1 1 1 3 3 3 1 3 3 3 3 3 1 3 3 2 1 2 1 2 2 3 2 2 2 1
 1 2 1 1 2 2 2 2 1 2 1 2 1 2 2 1 1 2 2 2 2 2 1 1 2 2 1 1 2 2 2 1 2 2 2 1 1
 2 1]
True


array([[4.70454545, 3.12272727, 1.41363636, 0.2       ],
       [6.25714286, 2.86190476, 4.85      , 1.63333333],
       [6.95      , 3.10666667, 5.86666667, 2.15333333],
       [5.53214286, 2.63571429, 3.96071429, 1.22857143],
       [5.24285714, 3.66785714, 1.5       , 0.28214286]])

# 将新实例分配给离中心点最近的镞

In [4]:
import numpy as np
X_new = np.array([[0,2,1,3], [3,4,5,6], [-3,5,4, 3], [5,2,3, 6]])
# 预测新实例所属的簇
y_new_predict = kmeans.predict(X_new)

In [5]:
print(y_new_predict)

[0 1 0 3]


# 为每个Kmeans采用软聚类 分数值为相似性分数 例如高斯径向基函数

In [6]:
kmeans.transform(X_new)

array([[ 5.60395927,  7.5222998 ,  8.59816841,  6.55076526,  6.1567886 ],
       [ 7.08357867,  5.56727206,  5.65230042,  5.66742167,  7.07704863],
       [ 8.79849137,  9.63620376, 10.33385214,  9.02921986,  9.12995323],
       [ 6.1240803 ,  4.98132169,  5.29545403,  4.93728784,  6.14691934]])

# 查看模型惯性

In [8]:
kmeans.inertia_

49.84932900432901

In [10]:
kmeans.score(X)

-49.849329004329